#include<iostream.h>
#include<conio.h>
void main()
{
clrscr()
int n;
cout<<"enter the number of terms";
cin>>n;
int i;
for(i=0;i<n;i++)
{
cin>>n[i];
}
int ele;
cout<<"enter the element to be searched";
cin>>ele;
int flag=0;
int j;
for(j=0;j<n:j++)
{
if(n[i]==ele)
   {
     flag=1;
     break;
     }
     }
   if(flag==1)
   {
   cout<<ele"is at position"<<i+1;
   }
   else
   {
   cout<<ele<<"wasc not found";
   }
   getch()
   }
