/*
<Auto-generated file information>
Created by: Anuraag
Created on 11/10/15 at 15:37 GMT +5:30
 */
#include<stdio.h>
#include<stdlib.h>

struct node
{
    float coef;
    int expox;
    int expoy;
    struct node *link;
};

struct node *create(struct node *);
struct node *insert_s(struct node *,float,int,int);
struct node *insert(struct node *,float,int,int);
void display(struct node *ptr);
void poly_add(struct node *,struct node *);
void poly_sub(struct node *,struct node *);
void poly_mult(struct node *,struct node *);
main( )
{
    struct node *start1=NULL,*start2=NULL;

    printf("Enter polynomial 1 :\n");
    start1=create(start1);

    printf("Enter polynomial 2 :\n");
    start2=create(start2);

    printf("Polynomial 1 is :  ");
    display(start1);
    printf("Polynomial 2 is :  ");
    display(start2);

    poly_add(start1, start2);
    poly_sub(start1, start2);
    poly_mult(start1, start2);
}/*End of main()*/

struct node *create(struct node *start)
{
    int i,n,ex,ey;
    float co;
    printf("Enter the number of terms : ");
    scanf("%d",&n);
    for(i=1;i<=n;i++)
    {
        printf("Enter coeficient for term %d : ",i);
        scanf("%f",&co);
        printf("Enter expoxnent (power of x)for term %d : ",i);
        scanf("%d",&ex);
        printf("Enter expoxnent (power of y)for term %d : ",i);
        scanf("%d",&ey);
        start=insert_s(start,co,ex,ey);
    }
    return start;
}/*End of create()*/
struct node *insert_s(struct node *start,float co,int ex,int ey)
{
    struct node *ptr,*tmp;
    tmp=(struct node *)malloc(sizeof(struct node));
    tmp->coef=co;
    tmp->expox=ex;
    tmp->expoy=ey;
    /*list empty or exp greater than first one */
    if(start==NULL || ex > start->expox)
    {
        tmp->link=start;
        start=tmp;
    }
    else
    {
        ptr=start;
        while(ptr->link!=NULL && ptr->link->expox >= ex)
            ptr=ptr->link;
        tmp->link=ptr->link;
        ptr->link=tmp;
    }
    return start;
}/*End of insert()*/

struct node *insert(struct node *start,float co,int ex, int ey)
{
    struct node *ptr,*tmp;
    tmp=(struct node *)malloc(sizeof(struct node));
    tmp->coef=co;
    tmp->expox=ex;
    tmp->expoy=ey;
    /*If list is empty*/
    if(start==NULL)
    {
        tmp->link=start;
        start=tmp;
    }
    else    /*Insert at the end of the list*/
    {
        ptr=start;
        while(ptr->link!=NULL)
            ptr=ptr->link;
        tmp->link=ptr->link;
        ptr->link=tmp;
    }
    return start;
}/*End of insert()*/

void display(struct node *ptr)
{
    if(ptr==NULL)
    {
        printf("Zero polynomial\n");
        return;
    }
    while(ptr!=NULL)
    {
        printf("(%.1fx^%dy^%d)", ptr->coef,ptr->expox,ptr->expoy);
        ptr=ptr->link;
        if(ptr!=NULL)
            printf(" + ");
        else
            printf("\n");
    }
}/*End of display()*/

void poly_add(struct node *p1,struct node *p2)
{
    struct node *start3;
    start3=NULL;

    while(p1!=NULL && p2!=NULL)
    {
        if((p1->expox>p2->expox) || (p1->expox==p2->expox)&&(p1->expoy>p2->expoy))
        {
            start3=insert(start3,p1->coef,p1->expox,p1->expoy);
            p1=p1->link;
        }
        else if((p2->expoy>p2->expoy) || (p1->expox==p2->expox)&&(p2->expoy>p1->expoy))
        {
            start3=insert(start3,p2->coef,p2->expox,p2->expoy);
            p2=p2->link;
        }
        else if((p1->expox==p2->expox)&&(p1->expoy==p2->expoy))
        {
            start3=insert(start3,p1->coef+p2->coef,p1->expox,p1->expoy);
            p1=p1->link;
            p2=p2->link;
        }
    }
    /*if poly2 has finished and elements left in poly1*/
    while(p1!=NULL)
    {
        start3=insert(start3,p1->coef,p1->expox,p1->expoy);
        p1=p1->link;
    }
    /*if poly1 has finished and elements left in poly2*/
    while(p2!=NULL)
    {
        start3=insert(start3,p2->coef,p2->expox,p2->expoy);
        p2=p2->link;
    }
    printf("Added polynomial is : ");
    display(start3);
}/*End of poly_add() */
void poly_sub(struct node *p1,struct node *p2)
{
    struct node *start3;
    start3=NULL;

    while(p1!=NULL && p2!=NULL)
    {
        if((p1->expox>p2->expox) || (p1->expox==p2->expox)&&(p1->expoy>p2->expoy))
        {
            start3=insert(start3,p1->coef,p1->expox,p1->expoy);
            p1=p1->link;
        }
        else if((p2->expoy>p2->expoy) || (p1->expox==p2->expox)&&(p2->expoy>p1->expoy))
        {
            start3=insert(start3,p2->coef,p2->expox,p2->expoy);
            p2=p2->link;
        }
        else if((p1->expox==p2->expox)&&(p1->expoy==p2->expoy))
        {
            start3=insert(start3,p1->coef-p2->coef,p1->expox,p1->expoy);
            p1=p1->link;
            p2=p2->link;
        }
    }
    /*if poly2 has finished and elements left in poly1*/
    while(p1!=NULL)
    {
        start3=insert(start3,p1->coef,p1->expox,p1->expoy);
        p1=p1->link;
    }
    /*if poly1 has finished and elements left in poly2*/
    while(p2!=NULL)
    {
        start3=insert(start3,p2->coef,p2->expox,p2->expoy);
        p2=p2->link;
    }
    printf("Subtracted polynomial is : ");
    display(start3);
}/*End of poly_sub() */

void poly_mult(struct node *p1, struct node *p2)
{
    struct node *start3;
    struct node *p2_beg = p2;
    start3=NULL;
    if(p1==NULL || p2==NULL)
    {
        printf("Multiplied polynomial is zero polynomial\n");
        return;
    }
    while(p1!=NULL)
    {
        p2=p2_beg;
        while(p2!=NULL)
        {
            start3=insert_s(start3,p1->coef*p2->coef,p1->expox+p2->expox,p1->expoy+p2->expoy);
            p2=p2->link;
        }
        p1=p1->link;
    }
    printf("Multiplied polynomial is : ");
    display(start3);
}/*End of poly_mult()*/
